### ISSUE TITLE
Code doubt

### ISSUE THREAD

**Issue by ankitsongara** [finlytics-hub/credit_risk_model#2]
```
loan_data['good_bad'] = np.where(loan_data.loc[:, 'loan_status'].isin(['Charged Off', 'Default',
                                                                       'Late (31-120 days)',
                                                                       'Does not meet the credit policy. Status:Charged Off']),
                                 0, 1)
```
Since we are classifying loans with the following loan_status values as being in default (bad, or 1):
Charged Off
Default
Late (31–120 days)
Does not meet the credit policy. Status:Charged Off
**Instead of 1, it should be 0 and 0 instead of 1 in the code.** 
Or am I not interpreting something correctly?

**Comment by finlytics-hub** [comment]
Hi there @ankitsongara 

The code is correct, however, the explanatory text in the post is wrong. Apologies for that - bad accounts should indeed be coded as 0 while good accounts as 1.

If we encode the target variable the other way around, the model coefficients have a risk of being misinterpreted. Consider this example: in the case of encoding bad accounts as 1, a +ve coefficient for DTI variable in a logistic regression model will indicate a higher risk. However, this is counterintuitive and may result in misunderstandings during model interpretation (since a higher DTI is generally always considered positive in terms of creditworthiness). So the way to work around this is to encode bad accounts as 0 and good accounts as 1.

Hope this would have helped.
